---
- hosts: webservers
  remote_user: alf
  become: yes
  
  tasks:
   
  - name: Add multiple repositories into the same file (1/4)
    yum_repository:
      name: CentOS-$releasever - Base
      description: Base CentOs YUM repo
      file: CentOS-Base
      baseurl: http://mirror.centos.org/centos/$releasever/os/$basearch/
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
      enabled: no
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      gpgcheck: yes

  - name: Add multiple repositories into the same file (2/4)
    yum_repository:
      name: CentOS-$releasever - Updates
      description: Updates CentOs YUM repo
      file: CentOS-Base
      baseurl: baseurl=http://mirror.centos.org/centos/$releasever/os/$basearch/
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
      enabled: no
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      gpgcheck: yes


  - name: Add multiple repositories into the same file (3/4)
    yum_repository:
      name: CentOS-$releasever - Extras
      description: Extras CentOs YUM repo
      file: CentOS-Base
      baseurl: http://mirror.centos.org/centos/$releasever/extras/$basearch/
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra
      enabled: no
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      gpgcheck: yes


  - name: Add multiple repositories into the same file (4/4)
    yum_repository:
      name: CentOS-$releasever - Plus
      description: Plus CentOs YUM repo
      file: CentOS-Base
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus&infra=$infra
      baseurl: http://mirror.centos.org/centos/$releasever/centosplus/$basearch/
      enabled: no
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      gpgcheck: yes
